version: 2
install_node_tooling: &install_node_tooling
  - run:
      name: Install node tooling
      command: |
        sudo apt install apt-transport-https &&
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - &&
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list &&
        sudo apt update &&
        sudo apt install yarn &&
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
build_frontend: &build_frontend
  - run:
      name: Build frontend bundle
      command: |
        source ~/.nvm/nvm.sh &&
        cd ${FRONTEND_ROOT} &&
        nvm install && nvm use &&
        yarn install &&
        sh build_bundle.sh
run_e2e_tests: &run_e2e_tests
  - run:
      name: End-to-end tests
      command: |
        source ~/.nvm/nvm.sh &&
        cd e2e_tests &&
        nvm install && nvm use &&
        yarn install &&
        yarn test
jobs:
  build_and_deploy:
    docker:
      - image: circleci/python:3.7.8-stretch-browsers
    steps:
      - checkout
      - run: sh .circleci/set_env_vars.sh
      # install gcloud
      - run: curl -o $HOME/google-cloud-sdk-303.0.0-linux-x86_64.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-303.0.0-linux-x86_64.tar.gz
      - run: tar zxf $HOME/google-cloud-sdk-303.0.0-linux-x86_64.tar.gz -C $HOME
      - run: CLOUDSDK_CORE_DISABLE_PROMPTS=1 $HOME/google-cloud-sdk/install.sh
      - run: echo 'source ${HOME}/google-cloud-sdk/path.bash.inc' >> $BASH_ENV
      - run: gcloud components install cloud-datastore-emulator beta
      - run: gcloud components update
      # install deps locally to enable unit testing
      - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install -r ${SERVER_CODE_ROOT}/src/requirements.txt
      - run: sudo pip install -r ${SERVER_CODE_ROOT}/dev_requirements.txt
      # Retrieve our secrets from the CircleCI environment
      - run: echo $APP_SECRETS | base64 --decode > ${SERVER_SRC_ROOT}/config.zip
      - run: unzip -o ${SERVER_SRC_ROOT}/config.zip -d ${SERVER_SRC_ROOT}
      # Deployment service account needs these roles:
      # - App Engine Deployer (to deploy new versions)
      # - App Engine Service Admin (to change versions)
      # - Cloud Datastore Index Admin (to update indexes)
      # - Storage Object Creator (to upload app files)
      # - Storage Object Viewer (to list app files)
      - run: echo $DEPLOYER_CLIENT_SECRETS | base64 --decode > ${HOME}/deployer_client_secrets.json
      - run: cd ${SERVER_CODE_ROOT} && sh run_tests/cloud_datastore.sh
      - <<: *install_node_tooling
      - <<: *build_frontend
      - run: gcloud auth activate-service-account --key-file ${HOME}/deployer_client_secrets.json
      - run: gcloud config set project $GCLOUD_PROJECT
      - run: gcloud app deploy --no-promote --project $GCLOUD_PROJECT -q -v $NEW_TROTTO_VERSION_ID ${SERVER_SRC_ROOT}/app.yaml ${SERVER_SRC_ROOT}/index.yaml
      - <<: *run_e2e_tests
      - run: gcloud app deploy --promote --project $GCLOUD_PROJECT -q -v $NEW_TROTTO_VERSION_ID ${SERVER_SRC_ROOT}/app.yaml ${SERVER_SRC_ROOT}/index.yaml
# TODO: Split into build/test and deploy jobs (latter is the only job that needs gcloud/deployment creds).
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
